### ISSUE TITLE
[BUG] Progress updates finish when all jobs have been dispatched (instead of when finished)

### ISSUE THREAD

**Issue by shreeve** [shreeve/vete#1]
Once all jobs have been dispatched for processing, the main loop exits.

It should actually keep showing progress updates until all jobs have **finished**.

Maybe, @ioquatix or @ahoward, could you guys take a quick look?

**Comment by ioquatix** [comment]
Can you link in the source code you think has a bug?

**Comment by shreeve** [comment]
Inside here, where it's processing the jobs:

https://github.com/shreeve/vete/blob/41e842dc51b31caee8acf99b5d2a63af096001e2/lib/vete.rb#L164-L190

Basically that code works great while dispatching jobs to be processed. Once it's done spawning off jobs, it'll happily finish and be done. But, it actually shouldn't really consider it's work done until all those child processes are actually completed, not just spawned.

**Comment by ioquatix** [comment]
You should use `thread.join` or some other synchronisation mechanism. It sounds like you understand the root cause of the issue.

**Comment by shreeve** [comment]
@ioquatix - Thank you! Yes, I was able to add some code after the main thread finished that just waiting for the worker to all return back. While it waits, it redraws every few moments.
